// Emoji catalog for the QR logo picker. Entries are "<char> <search terms>" so
// the data stays readable inline; parsed once into groups below.
// Kept to sequences of at most 8 UTF-16 units — the API's cap for text logos.

const CATALOG: Record<string, string[]> = {
  smileys: [
    '😀 grin happy smile',
    '😃 smile happy open',
    '😄 laugh happy smile',
    '😁 beam grin teeth',
    '😆 laugh squint',
    '😅 sweat laugh nervous',
    '🤣 rofl laugh floor',
    '😂 joy tears laugh',
    '🙂 slight smile',
    '🙃 upside down silly',
    '😉 wink',
    '😊 blush smile happy',
    '😇 halo angel innocent',
    '🥰 love hearts adore',
    '😍 heart eyes love',
    '🤩 star struck wow',
    '😘 kiss blow',
    '😋 yum tasty tongue',
    '😜 tongue wink crazy',
    '🤪 zany goofy silly',
    '😎 cool sunglasses',
    '🤓 nerd geek glasses',
    '🧐 monocle inspect',
    '🤔 think hmm',
    '😐 neutral meh',
    '😴 sleep zzz tired',
    '🤯 mind blown explode',
    '🥳 party celebrate',
    '😱 scream shock fear',
    '😭 cry sob tears',
    '😡 angry mad rage',
    '🥺 pleading puppy eyes',
    '🤠 cowboy hat',
    '👻 ghost spooky',
    '💀 skull dead',
    '👽 alien ufo',
    '🤖 robot bot ai',
    '💩 poop',
    '🎃 pumpkin halloween',
    '😺 cat smile',
  ],
  people: [
    '👋 wave hello hi',
    '🤚 hand raised',
    '✌️ peace victory',
    '🤞 fingers crossed luck',
    '🤙 call shaka',
    '👌 ok perfect',
    '👍 thumbs up like yes',
    '👎 thumbs down no',
    '👏 clap applause',
    '🙌 raise hands praise',
    '🤝 handshake deal',
    '🙏 pray thanks please',
    '💪 muscle strong flex',
    '✍️ write hand pen',
    '👀 eyes look see',
    '🧠 brain mind smart',
    '👶 baby',
    '🧑 person adult',
    '👩 woman',
    '👨 man',
    '🧓 older elder',
    '👮 police cop officer',
    '👷 worker builder construction',
    '🕵️ detective spy',
    '👩‍⚕️ doctor nurse health',
    '👨‍🍳 chef cook',
    '🧑‍🎓 student graduate',
    '🧑‍🏫 teacher',
    '🧑‍💻 developer coder tech',
    '🦸 hero superhero',
    '🧙 wizard mage magic',
    '🧚 fairy',
    '🧜 mermaid merperson',
    '🎅 santa christmas',
    '👑 crown king queen royal',
    '🫶 heart hands love',
  ],
  animals: [
    '🐶 dog puppy',
    '🐱 cat kitten',
    '🐭 mouse',
    '🐹 hamster',
    '🐰 rabbit bunny',
    '🦊 fox',
    '🐻 bear',
    '🐼 panda',
    '🐨 koala',
    '🐯 tiger',
    '🦁 lion',
    '🐮 cow',
    '🐷 pig',
    '🐸 frog',
    '🐵 monkey',
    '🐔 chicken hen',
    '🐧 penguin',
    '🐦 bird',
    '🦆 duck',
    '🦅 eagle',
    '🦉 owl',
    '🦄 unicorn',
    '🐝 bee honey',
    '🦋 butterfly',
    '🐞 ladybug beetle',
    '🐢 turtle',
    '🐍 snake',
    '🐙 octopus',
    '🦀 crab',
    '🐠 fish tropical',
    '🐬 dolphin',
    '🐳 whale',
    '🦈 shark',
    '🐘 elephant',
    '🦒 giraffe',
    '🐴 horse',
    '🐑 sheep',
    '🦌 deer',
    '🐕 dog leash',
    '🐈 cat house',
    '🦔 hedgehog',
    '🦖 dinosaur trex',
    '🐾 paw prints',
  ],
  nature: [
    '🌵 cactus',
    '🌲 tree evergreen',
    '🌳 tree deciduous',
    '🌴 palm tree beach',
    '🌱 seedling sprout grow',
    '🌿 herb leaf plant',
    '🍀 clover luck four',
    '🍃 leaves wind',
    '🍂 leaves autumn fall',
    '🍁 maple leaf autumn',
    '🌾 wheat grain rice',
    '💐 bouquet flowers',
    '🌷 tulip flower',
    '🌹 rose flower love',
    '🌺 hibiscus flower',
    '🌸 blossom cherry sakura',
    '🌼 daisy flower',
    '🌻 sunflower',
    '🌞 sun face bright',
    '🌙 moon crescent night',
    '⭐ star',
    '🌟 star glowing sparkle',
    '✨ sparkles shine magic',
    '⚡ lightning bolt power',
    '🔥 fire flame hot lit',
    '💥 boom explosion',
    '☀️ sun sunny',
    '🌈 rainbow pride',
    '☁️ cloud',
    '🌧️ rain cloud',
    '❄️ snowflake cold winter',
    '💧 droplet water',
    '🌊 wave ocean sea',
    '🌍 earth globe world',
    '🌋 volcano',
    '🏔️ mountain snow',
  ],
  food: [
    '🍎 apple red fruit',
    '🍐 pear fruit',
    '🍊 orange tangerine fruit',
    '🍋 lemon fruit sour',
    '🍌 banana fruit',
    '🍉 watermelon fruit',
    '🍇 grapes fruit',
    '🍓 strawberry fruit',
    '🫐 blueberries fruit',
    '🍒 cherries fruit',
    '🍑 peach fruit',
    '🥭 mango fruit',
    '🍍 pineapple fruit',
    '🥥 coconut',
    '🥝 kiwi fruit',
    '🍅 tomato',
    '🥑 avocado',
    '🥦 broccoli veg',
    '🥕 carrot veg',
    '🌽 corn maize',
    '🌶️ chili pepper spicy',
    '🥐 croissant pastry',
    '🍞 bread loaf',
    '🥖 baguette bread',
    '🧀 cheese',
    '🥚 egg',
    '🍳 fried egg cooking',
    '🥞 pancakes',
    '🥓 bacon',
    '🍔 burger hamburger',
    '🍟 fries chips',
    '🍕 pizza slice',
    '🌭 hotdog',
    '🥪 sandwich',
    '🌮 taco',
    '🌯 burrito wrap',
    '🥗 salad greens',
    '🍜 noodles ramen soup',
    '🍝 pasta spaghetti',
    '🍣 sushi',
    '🍦 ice cream soft serve',
    '🍩 donut doughnut',
    '🍪 cookie biscuit',
    '🎂 cake birthday',
    '🧁 cupcake',
    '🍫 chocolate bar',
    '🍬 candy sweet',
    '🍯 honey pot',
    '☕ coffee tea hot',
    '🍵 tea green matcha',
    '🧋 boba bubble tea',
    '🍺 beer pint',
    '🍷 wine glass',
    '🍸 cocktail martini',
    '🥂 cheers toast',
  ],
  activity: [
    '⚽ soccer football',
    '🏀 basketball',
    '🏈 football american',
    '⚾ baseball',
    '🎾 tennis',
    '🏐 volleyball',
    '🏉 rugby',
    '🎱 pool billiards eight',
    '🏓 ping pong table tennis',
    '🏸 badminton',
    '🥊 boxing glove fight',
    '⛳ golf',
    '🏹 archery bow arrow',
    '🎣 fishing',
    '🏂 snowboard',
    '🎿 ski',
    '🏄 surf',
    '🚴 cycling bike',
    '🏃 run running',
    '🧘 yoga meditate zen',
    '🎯 dart target bullseye',
    '🪁 kite',
    '🎮 game controller gaming',
    '🕹️ joystick arcade',
    '🎲 dice game random',
    '🧩 puzzle piece',
    '♟️ chess pawn strategy',
    '🎭 theater masks drama',
    '🎨 art palette paint',
    '🧵 thread sewing',
    '🎼 music score notes',
    '🎤 mic microphone sing',
    '🎧 headphones audio music',
    '🎷 saxophone jazz',
    '🎸 guitar rock',
    '🎹 piano keyboard music',
    '🎺 trumpet brass',
    '🎻 violin strings',
    '🥁 drum beat',
    '🏆 trophy win champion',
    '🥇 gold medal first',
    '🎖️ medal military award',
    '🎉 party popper celebrate',
    '🎊 confetti celebrate',
    '🎈 balloon party',
    '🎁 gift present box',
    '🎪 circus tent',
    '🎟️ ticket admission',
  ],
  travel: [
    '🚗 car auto drive',
    '🚕 taxi cab',
    '🚙 suv car',
    '🚌 bus',
    '🏎️ race car fast',
    '🚓 police car',
    '🚑 ambulance',
    '🚒 fire truck engine',
    '🚚 truck delivery',
    '🚜 tractor farm',
    '🛴 scooter kick',
    '🚲 bicycle bike',
    '🛵 moped scooter',
    '🏍️ motorcycle',
    '🚨 siren emergency alert',
    '🚂 train steam locomotive',
    '🚆 train rail',
    '🚇 metro subway',
    '🚊 tram',
    '✈️ airplane flight fly',
    '🛫 takeoff departure',
    '🛬 landing arrival',
    '🚀 rocket launch space',
    '🛸 ufo saucer',
    '🚁 helicopter',
    '⛵ sailboat sailing',
    '🚤 speedboat',
    '🛳️ cruise ship passenger',
    '⚓ anchor',
    '⛽ fuel gas station',
    '🚧 construction barrier',
    '🗺️ map world travel',
    '🗽 statue liberty new york',
    '🗼 tokyo tower',
    '🏰 castle',
    '🎡 ferris wheel fair',
    '🎢 roller coaster',
    '⛲ fountain',
    '🏖️ beach umbrella',
    '🏝️ island desert tropical',
    '🏕️ camping tent',
    '🏠 house home',
    '🏢 office building work',
    '🏬 store department shop',
    '🏭 factory industry',
    '🌃 city night skyline',
    '🌉 bridge night',
  ],
  objects: [
    '⌚ watch time',
    '📱 phone mobile smartphone',
    '💻 laptop computer',
    '⌨️ keyboard typing',
    '🖥️ desktop computer monitor',
    '🖨️ printer print',
    '🖱️ mouse computer',
    '💾 floppy disk save',
    '💿 disc cd',
    '📷 camera photo',
    '📹 video camera record',
    '🎥 movie camera film',
    '🎬 clapper film action',
    '📺 tv television',
    '📻 radio',
    '🎙️ studio mic podcast',
    '⏰ alarm clock time',
    '⏳ hourglass time wait',
    '📡 satellite dish signal',
    '🔋 battery power',
    '🔌 plug electric',
    '💡 bulb idea light',
    '🔦 flashlight torch',
    '🕯️ candle',
    '💸 money flying cash spend',
    '💵 dollar cash money',
    '💰 money bag rich',
    '💳 credit card pay',
    '💎 gem diamond',
    '⚖️ scales balance justice law',
    '🧰 toolbox tools',
    '🔧 wrench fix tool',
    '🔨 hammer build',
    '⚙️ gear settings cog',
    '🔩 bolt nut screw',
    '🔒 lock secure closed',
    '🔓 unlock open',
    '🔑 key access',
    '🔗 link chain url',
    '📎 paperclip attach',
    '📌 pin pushpin',
    '📏 ruler measure',
    '✂️ scissors cut',
    '🗑️ trash bin delete',
    '📦 package box shipping',
    '📫 mailbox mail',
    '✉️ envelope email mail',
    '📤 outbox send',
    '📥 inbox receive',
    '📜 scroll document',
    '📄 page document file',
    '📊 bar chart stats data',
    '📈 chart up growth trend',
    '📉 chart down decline',
    '🗓️ calendar date schedule',
    '📁 folder file',
    '📰 newspaper news press',
    '📓 notebook notes',
    '📚 books library read',
    '📖 book open read',
    '🔖 bookmark tag',
    '🖊️ pen write',
    '🖌️ paintbrush',
    '📝 memo note write',
    '✏️ pencil write edit',
    '🔍 search magnify find',
    '🛒 cart shopping buy',
    '🛍️ shopping bags retail',
    '🧾 receipt invoice bill',
    '🩺 stethoscope health doctor',
    '💊 pill medicine',
    '🧪 test tube lab science',
    '🔬 microscope science',
    '🔭 telescope space',
    '🧭 compass navigate',
    '🧲 magnet',
    '☂️ umbrella rain',
    '🧿 evil eye amulet',
  ],
  symbols: [
    '❤️ heart red love',
    '🧡 heart orange',
    '💛 heart yellow',
    '💚 heart green',
    '💙 heart blue',
    '💜 heart purple',
    '🖤 heart black',
    '🤍 heart white',
    '💔 broken heart',
    '💕 two hearts love',
    '💖 sparkling heart',
    '💯 hundred score perfect',
    '✅ check tick done yes',
    '❌ cross x no wrong',
    '⭕ circle red',
    '❗ exclamation important',
    '❓ question help',
    '⚠️ warning caution',
    '🚫 forbidden no ban',
    '⛔ no entry stop',
    '🛑 stop sign',
    '♻️ recycle green eco',
    '🔰 beginner leaf',
    '⚜️ fleur de lis',
    '🔱 trident',
    '☮️ peace',
    '☯️ yin yang balance',
    '🕉️ om',
    '✝️ cross christian',
    '☪️ star crescent islam',
    '✡️ star of david',
    '☸️ dharma wheel',
    '🔯 six pointed star',
    '♈ aries zodiac',
    '♉ taurus zodiac',
    '♊ gemini zodiac',
    '♋ cancer zodiac',
    '♌ leo zodiac',
    '♍ virgo zodiac',
    '♎ libra zodiac',
    '♏ scorpio zodiac',
    '♐ sagittarius zodiac',
    '♑ capricorn zodiac',
    '♒ aquarius zodiac',
    '♓ pisces zodiac',
    '⚛️ atom science',
    '🔆 brightness bright',
    '〽️ part alternation',
    '🌀 cyclone spiral swirl',
    '💤 zzz sleep',
    '♿ accessible wheelchair',
    '🅿️ parking p',
    '🆕 new',
    '🆓 free',
    '🆗 ok',
    '🔝 top up',
    '🔞 eighteen adult',
    '📶 signal bars network',
    '🔇 mute silent',
    '🔊 speaker loud volume',
    '🔔 bell notification',
    '#️⃣ hash number',
    '1️⃣ one number',
    '2️⃣ two number',
    '3️⃣ three number',
  ],
}

export interface EmojiGroup {
  name: string
  items: { char: string; terms: string }[]
}

export const EMOJI_GROUPS: EmojiGroup[] = Object.entries(CATALOG).map(
  ([name, entries]) => ({
    name,
    items: entries.map((entry) => {
      const sep = entry.indexOf(' ')
      return { char: entry.slice(0, sep), terms: entry.slice(sep + 1) }
    }),
  }),
)

/** Substring match over an emoji's search terms. Empty query matches nothing. */
export function searchEmoji(query: string): string[] {
  const q = query.trim().toLowerCase()
  if (!q) return []
  const hits: string[] = []
  for (const group of EMOJI_GROUPS)
    for (const item of group.items)
      if (item.terms.includes(q)) hits.push(item.char)
  return hits
}
